### ISSUE TITLE
Modal com informações dos minicursos e palestras

### ISSUE THREAD

**Issue by Yudi** [cacic-fct/site-secompp-2022#2]
Ao clicar num evento tabela de horário, um modal com as informações do minicurso deve ser apresentado. Os dados do modal devem ser alimentados através de um objeto ao invés de haver um modal com informações hardcoded para cada evento.

Documentação relevante: https://sveltestrap.js.org/

O design fica a critério dos desenvolvedores, mas deve seguir o estilo do evento e ser aprovado pelos avaliadores.
A sugestão é fazer uso de diferentes `font-weight`.

**Comment by Igor-MPereira** [comment]
Os eventos da tabela e as informações do minucurso vão ser buscados de uma api ou de um objeto/json estático?

Tem algum documento ou especificação para a estrutura do objeto?

**Comment by Yudi** [comment]
A intenção é manter o projeto simples, então as informações devem estar em um objeto/json, mas pode ser que isso venha a mudar depois. A implementação e estrutura ficam a critério do desenvolvedor. 

O objeto deve conter, não necessariamente nessa ordem, as seguintes informações a serem exibidas no modal:
Nome do evento
Data
Horário de início
Horário de término
Localização em texto (ex: Laboratório 10B)
Informações de quem irá ministrar, podendo ser mais de uma pessoa 
Descrição longa do evento

Para praticidade, a tabela de horário pode ser hardcoded ao invés de ser gerada dinamicamente pelas informações de horário. 

Pode ser que adaptações precisem ser feitas quando o cronograma oficial for liberado.

**Comment by Yudi** [comment]
@Igor-MPereira

**Comment by Igor-MPereira** [comment]
Vai existir algum caso de dois eventos no mesmo horário no mesmo dia?

**Comment by Yudi** [comment]
Na última SECOMPP isso aconteceu, então deve-se considerar que sim.
